# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-11-26 01:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191125_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 26, 1, 11, 25, 590959, tzinfo=utc)),
        ),
    ]
